# Generated by Django 3.1 on 2020-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('year', models.DateField()),
                ('visual_description', models.TextField()),
                ('contextual_description', models.TextField()),
            ],
        ),
    ]
