# Generated by Django 3.1 on 2020-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0002_auto_20200825_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.URLField(),
        ),
    ]
