# Generated by Django 3.1 on 2020-08-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0003_auto_20200827_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='century',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
