# Generated by Django 3.1 on 2020-08-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='link',
            field=models.CharField(default='det', max_length=200),
            preserve_default=False,
        ),
    ]
