# Generated by Django 3.1 on 2020-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0007_artwork_thumb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('generation', models.CharField(
                    choices=[('human generated', 'human generated'), ('auto generated', 'auto generated')],
                    max_length=50)),
            ],
        ),
    ]
