# Generated by Django 3.1 on 2020-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0010_question_answer_sentence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='revised',
            field=models.BooleanField(default=False),
        ),
    ]
