# Generated by Django 3.1 on 2020-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('artworks', '0011_question_answer_revised'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
    ]
