# Generated by Django 3.1 on 2020-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_auto_20200926_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answer',
            name='question_error_type',
            field=models.CharField(choices=[('One character question', 'One character question'), ('Too long question', 'Too long question'), ('What is? as question or two words question', 'What is? as question or two words question'), ('Commission related wrong question', 'Commission related wrong question'), ('Who instead of Where or viceversa', 'Who instead of Where or viceversa'), ('What instead of Where or viceversa', 'What instead of Where or viceversa'), ('Was instead of were or viceversa', 'Was inted of were or viceversa'), ('Part of the sentence repeated', 'Part of the sentence repeated'), ('Indefinite article instead of definite article or viceversa', 'Indefinite article instead of definite article or viceversa'), ('No sense question', 'No sense question'), ('Correct', 'Correct'), ('Unrevised', 'Unrevised')], default='Unrevised', max_length=500),
        ),
    ]
