# Generated by Django 4.1.7 on 2024-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0028_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="question_language",
            field=models.CharField(default="English", max_length=50),
        ),
    ]
